dataset_path: csv
dataset_kwargs:
  data_files: dataset/vtwt/vtwt.csv
task: vtwt
test_split: train
output_type: multiple_choice
doc_to_visual: !function utils.vtwt_doc_to_visual
doc_to_text: !function utils.vtwt_doc_to_text
doc_to_target: !function utils.vtwt_doc_to_target
doc_to_choice: !function utils.vtwt_doc_to_choice
process_results: !function utils.vtwt_process_results
metric_list:
  - metric: acc
    aggregation: mean
    higher_is_better: true
lmms_eval_specific_kwargs:
  default:
    pre_prompt: ""
    post_prompt: ""
  # llava:
  #   pre_prompt: "blablabla"
  #   post_prompt: "hohoho"
metadata:
  - version: 0.0